stages:
  - build
  - push
  - run
  - clean

build:
  stage: build
  script:
    # 打包
    - /usr/local/maven/apache-maven-3.5.2/bin/mvn clean package
    - cp target/iToken-config-1.0.0-SNAPSHOT.jar docker
    - cd docker
    - docker build -t 192.168.137.132:5000/itoken-config-1.0.1 .

push:
  stage: push
  script:
    - docker pull 192.168.137.132:5000/itoken-config-1.0.1

run:
  stage: run
  script:
    - cd docker
    # 停止容器
    - docker-compose down
    # 运行容器
    - docker-compose up -d

clean:
  stage: clean
  script:
    # 清除没有运行的镜像
    - docker image prune -a -f