spring:
  application:
    name: iToken-eureka
  boot:
    admin:
      client:
        url: http://localhost:18230
  zipkin:
    base-url: http://localhost:18210

server:
  port: 18110

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoint:
    health:
    show-details: always
  endpoints:
    web:
      exposure:
        include: "*"