spring:
  application:
    name: iToken-web-admin
  thymeleaf:
    cache: false #开发时关闭页面缓存
    mode: HTML5 #使用非严格 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html


fergn:
  hystrix:
    enabled: true