itoken:
  ip:
    eureka: localhost
    admin: localhost
    zipkin: localhost
    zuul: localhost
  component:
    eureka: 18110
    admin: 18230
    zipkin: 18210
    zuul: 18220

spring:
  application:
    name: iToken-eureka

server:
  port: ${itoken.component.eureka}

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:18110/eureka/

management:
  endpoint:
    health:
    show-details: always
  endpoints:
    web:
      exposure:
        include: "*"