spring:
  application:
    name: iToken-web-admin
  thymeleaf:
    cache: false #开发时关闭页面缓存
    mode: LEGACYHTML5 #使用非严格 HTML
    encoding: UTF-8
    content-type: text/html

fergn:
  hystrix:
    enabled: true