spring:
  application:
    name: iToken-zuul

server:
  port: {itoken.component.zuul}

zuul:
  routes:
    api-a:
      path: /apo/a/**
      serviceId: iToken-web-admin-ribbon11
    api-b:
      path: /apo/b/**
      serviceId: iToken-web-admin-ribbon12
