spring:
  application:
    name: com.itoken

server:
  port: ${itoken.component.eureka}

eureka:
  instance:
    hostname: ${itoken.ip.eureka}
  client:
    # 表示是否将自己注册到Eureka，因为要构建集群环境，需要将自己注册到集群，此处设置为true
    registerWithEureka: true
    # 表示是否从Eureka 获取注册信息，如果是单一节点，不需要同步其他 Eureka 节点，但此处为集群，所以设置为true
    fetchRegistry: true
    service-url:
      defaultZone: defaultZone: http://${itoken.ip.eureka-1}:${itoken.component.eureka-1}/eureka/,http://${itoken.ip.eureka-2}:${itoken.component.eureka-2}/eureka/,http://${itoken.ip.eureka-3}:${itoken.component.eureka-3}/eureka/
