spring:
  application:
    name: iToken-eureka

server:
  port: {itoken.ip.eureka}

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:18110/eureka/

management:
  endpoint:
    health:
    show-details: always
  endpoints:
    web:
      exposure:
        include: "*"