spring:
  application:
    name: iToken-admin
  zipkin:
    base-url: http://192.168.137.133:8210

server:
  port: {itoken.component.admin}

management:
  endpoint:
    health:
    show-details: always
  endpoints:
    web:
      exposure:
        include: health,info