spring:
  boot:
    admin:
      client:
        url: http://192.168.137.133:8230

management:
  endpoint:
    health:
    show-details: always
  endpoints:
    web:
      exposure:
        include: "*"