spring:
  application:
    name: iToken-admin

server:
  port: ${itoken.component.admin}

management:
  endpoint:
    health:
    show-details: always
  endpoints:
    web:
      exposure:
        include: "*"