spring:
  boot:
    admin:
      client:
        url: http://{itoken.ip.admin}:{itoken.component.admin}

management:
  endpoint:
    health:
    show-details: always
  endpoints:
    web:
      exposure:
        include: "*"