spring:
  application:
    name: iToken-eureka

server:
  port: 18110

eureka:
  instance:
    hostname: {itoken.ip.eureka}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://{itoken.ip.eureka}:{itoken.component.eureka}/eureka/

management:
  endpoint:
    health:
    show-details: always
  endpoints:
    web:
      exposure:
        include: "*"