spring:
  application:
    name: iToken-zipkin
server:
  port: 8210

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
    show-details: always
  endpoints:
    web:
      exposure:
        include: health,info