spring:
  application:
    name: iToken-eureka

server:
  port: 18110

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:18110/eureka/