spring:
  application:
    name: iToken-eureka

server:
  port: 18110

eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否将自己注册到Eureka，因为要构建集群环境，需要将自己注册到集群，此处设置为true
    registerWithEureka: false
    # 表示是否从Eureka 获取注册信息，如果是单一节点，不需要同步其他 Eureka 节点，但此处为集群，所以设置为true
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
