spring:
  application:
    name: iToken-zuul

server:
  port: 18210


zuul:
  routes:
    api-admin:
      path: /api/admin/**
      serviceId: iToken-admin
    api-zipkin:
      path: /api/zuul/**
      serviceId: iToken-zipkin

